import type { NextPage } from 'next';
import Head from 'next/head';
import BaseLayout from 'components/BaseLayout';

const IdeaDetails: NextPage = () => {
	return (
		<>
			<Head>
				<title>Bucket List | share your idea</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<BaseLayout>Details</BaseLayout>
		</>
	);
};

export default IdeaDetails;
