import { type NextPage } from "next";
import Head from 'next/head';
import type { Idea } from '@prisma/client';
import BaseLayout from 'components/BaseLayout';
import IdeaCard from 'components/IdeaCard';
import { Stack } from '@mantine/core';
import { prisma } from 'server/db/client';

interface Props {
  ideas: string;
}

const Home: NextPage<Props> = (props) => {
  const { ideas } = props;
  const parsedIdeas: Idea[] = JSON.parse(ideas);
  const cards = parsedIdeas.map((idea) => <IdeaCard key={idea.id} idea={idea} />)

  return (
    <>
      <Head>
        <title>Bucket List | share your idea</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <Stack style={{ maxWidth: '600px', margin: '0 auto' }}>
          {cards}
        </Stack>
      </BaseLayout>
    </>
  );
};

export default Home;

export async function getStaticProps() {
  const ideas = await prisma.idea.findMany();

  return {
    props: {
      ideas: JSON.stringify(ideas),
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 60 * 60 * 24, // In seconds
  }
}
